version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
  nextjs:
    image: nextjs:13-alpine
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: yarn dev
