version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: jamsync
    ports:
      - 5432:5432
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379